# Server config

# Server address
server-addr: localhost

# Server TCP port
tcp-port: 6666

# Registry host
registry-host: localhost

# RMI Registry port
registry-port: 7777

# Socket timeout 
socket-timeout: 100000 # comments may be written after values