# Client configuration file

# Server address
server-addr: localhost

# Server TCP port
tcp-port: 6666

# Registry name
registry-name: winsome-server

# RMI Registry port
registry-port: 7777

# Socket timeout (in milliseconds)
socket-timeout: 10000 # comments may be written after values