# Server config

# Server address
server-addr: 192.168.1.2

# Server TCP port
tcp-port: 6666

# Server UDP port
udp-port: 33333

# Multicast address
multicast-addr: 239.255.32.32

# Multicast port
multicast-port: 44444

# Registry host
registry-host: localhost

# RMI Registry port
registry-port: 7777

# Socket timeout 
socket-timeout: 100000 # comments may be written after values

# Interval for reward computation
reward-interval: 1000

# Percentage of the reward going to the author
reward-percentage: 70